-- 002_search.sql — enable Lakebase Search (BM25). Requires per-project Search
-- Beta enablement; the runner skips this file cleanly if the extension is
-- absent.
--
-- We install ONLY lakebase_text (the `lakebase_bm25` index type for BM25
-- keyword search). The actual searchable table + BM25 index are built on a
-- SYNCED gold table (see resources/lakebase.yml), not here — a synced table
-- carries governed lakehouse data + a generated tsvector, and the BM25 index is
-- built post-sync. The earlier hand-created northpeak.inventory_notes scaffold
-- (with lakebase_bm25 + lakebase_ann on a toy vector(8)) was unused by the app
-- and has been removed; lakebase_vector/ANN is not installed (BM25-only).
CREATE EXTENSION IF NOT EXISTS lakebase_text;
